-- ==============================================================================
-- KINGSNAME CRM — Haute Sartorial & Bespoke Tailoring
-- Official Supabase (PostgreSQL 15+) Database Schema & Seed Data
-- ==============================================================================
-- Инструкция по установке:
-- 1. Зайдите в ваш проект Supabase (https://supabase.com/dashboard)
-- 2. Откройте вкладку "SQL Editor" в левом меню
-- 3. Нажмите "New query"
-- 4. Вставьте весь этот код и нажмите "Run" (зеленая кнопка)
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ------------------------------------------------------------------------------
-- 0. Функция автоматического обновления поля update_time
-- ------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.update_time = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ------------------------------------------------------------------------------
-- 1. Table: sys_access_code (8-значные коды доступа сотрудников)
-- ------------------------------------------------------------------------------
DROP TABLE IF EXISTS sys_access_code CASCADE;
CREATE TABLE sys_access_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(8) NOT NULL,
    user_id BIGINT NOT NULL,
    user_name VARCHAR(64) NOT NULL,
    role_code VARCHAR(32) NOT NULL DEFAULT 'consultant',
    valid_type SMALLINT NOT NULL DEFAULT 1, -- 1 = Смена (8-12ч), 2 = 1 День (24ч), 3 = Бессрочно
    expire_time TIMESTAMPTZ NULL,
    status SMALLINT NOT NULL DEFAULT 0, -- 0 = Активен, 1 = Отозван, 2 = Заблокирован
    failed_attempts INT NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ NULL,
    creator VARCHAR(64) DEFAULT '',
    create_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updater VARCHAR(64) DEFAULT '',
    update_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE UNIQUE INDEX uk_code_active ON sys_access_code (code) WHERE deleted = false;
CREATE INDEX idx_access_code_user_id ON sys_access_code (user_id);
CREATE INDEX idx_access_code_status ON sys_access_code (status);

CREATE TRIGGER trg_sys_access_code_update_time
    BEFORE UPDATE ON sys_access_code
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ------------------------------------------------------------------------------
-- 2. Table: sys_login_log (Журнал аудита авторизаций по кодам)
-- ------------------------------------------------------------------------------
DROP TABLE IF EXISTS sys_login_log CASCADE;
CREATE TABLE sys_login_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(8) NOT NULL,
    user_name VARCHAR(64) DEFAULT '',
    role_code VARCHAR(32) DEFAULT '',
    ip VARCHAR(64) NOT NULL,
    user_agent VARCHAR(256) DEFAULT '',
    result_status SMALLINT NOT NULL, -- 1 = Успех, 0 = Ошибка, 2 = Заблокирован (RateLimit/Bruteforce)
    result_msg VARCHAR(256) DEFAULT '',
    login_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_login_log_time ON sys_login_log (login_time);
CREATE INDEX idx_login_log_code ON sys_login_log (code);

-- ------------------------------------------------------------------------------
-- 3. Table: kings_client (Картотека VIP-клиентов KINGSNAME)
-- ------------------------------------------------------------------------------
DROP TABLE IF EXISTS kings_client CASCADE;
CREATE TABLE kings_client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    phone VARCHAR(32) NOT NULL,
    city VARCHAR(64) NOT NULL DEFAULT 'Грозный',
    instagram VARCHAR(64) DEFAULT '',
    vip_level SMALLINT NOT NULL DEFAULT 1, -- 1 = Classic VIP, 2 = Gold VIP, 3 = Bespoke Club Elite
    total_spent NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    notes TEXT DEFAULT '',
    creator VARCHAR(64) DEFAULT '',
    create_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updater VARCHAR(64) DEFAULT '',
    update_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX idx_client_phone ON kings_client (phone);
CREATE INDEX idx_client_city ON kings_client (city);

CREATE TRIGGER trg_kings_client_update_time
    BEFORE UPDATE ON kings_client
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ------------------------------------------------------------------------------
-- 4. Table: kings_order (Заказы, индивидуальные мерки и 6 этапов воронки)
-- ------------------------------------------------------------------------------
DROP TABLE IF EXISTS kings_order CASCADE;
CREATE TABLE kings_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(32) NOT NULL,
    client_id BIGINT NOT NULL,
    client_name VARCHAR(128) NOT NULL,
    client_phone VARCHAR(32) NOT NULL,
    channel VARCHAR(32) NOT NULL DEFAULT 'INSTAGRAM', -- INSTAGRAM, WEBSITE, SALON_GROZNY, PHONE
    product_type VARCHAR(64) NOT NULL, -- Костюм-тройка, Костюм-двойка, Смокинг, Пальто, Сорочка
    order_type VARCHAR(16) NOT NULL DEFAULT 'BESPOKE', -- BESPOKE, RTW
    status VARCHAR(32) NOT NULL DEFAULT 'LEAD', -- LEAD, APPOINTMENT, FITTING, PAYMENT_AGREED, TAILORING, DELIVERED, CANCELLED
    
    -- Анатомические мерки Bespoke
    height INT NULL,
    chest NUMERIC(5, 1) NULL,
    waist NUMERIC(5, 1) NULL,
    hips NUMERIC(5, 1) NULL,
    shoulder_width NUMERIC(5, 1) NULL,
    sleeve_length NUMERIC(5, 1) NULL,
    trouser_length NUMERIC(5, 1) NULL,
    
    -- Спецификация костюма
    fabric_brand VARCHAR(64) DEFAULT 'Loro Piana',
    fabric_sku VARCHAR(64) DEFAULT '',
    fabric_color VARCHAR(32) DEFAULT 'Royal Navy',
    lapel_type VARCHAR(32) DEFAULT 'Notch', -- Notch, Peak, Shawl
    fit_type VARCHAR(32) DEFAULT 'Slim Fit', -- Slim Fit, Regular Classic, Bespoke Silhouette
    monogram VARCHAR(32) DEFAULT '',
    button_type VARCHAR(32) DEFAULT 'Natural Horn', -- Natural Horn, Mother of Pearl, Corozo
    tailor_notes TEXT DEFAULT '',
    
    -- Финансы
    total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    deposit_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    balance_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    payment_method VARCHAR(32) DEFAULT 'Наличные',
    payment_status VARCHAR(32) NOT NULL DEFAULT 'PENDING', -- PENDING, PARTIAL, PAID
    
    -- Сроки и записи
    appointment_date TIMESTAMPTZ NULL,
    target_completion_date DATE NULL,
    delivery_date TIMESTAMPTZ NULL,
    
    creator VARCHAR(64) DEFAULT '',
    create_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updater VARCHAR(64) DEFAULT '',
    update_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE UNIQUE INDEX uk_order_no_active ON kings_order (order_no) WHERE deleted = false;
CREATE INDEX idx_order_client_id ON kings_order (client_id);
CREATE INDEX idx_order_status ON kings_order (status);
CREATE INDEX idx_order_channel ON kings_order (channel);
CREATE INDEX idx_order_create_time ON kings_order (create_time);

CREATE TRIGGER trg_kings_order_update_time
    BEFORE UPDATE ON kings_order
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ------------------------------------------------------------------------------
-- 5. Table: kings_inventory (Склад готовых изделий и премиальных тканей)
-- ------------------------------------------------------------------------------
DROP TABLE IF EXISTS kings_inventory CASCADE;
CREATE TABLE kings_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type VARCHAR(32) NOT NULL, -- SUIT, JACKET, TROUSERS, SHIRT, FABRIC, ACCESSORY
    sku VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    size VARCHAR(16) NULL,
    height_category VARCHAR(16) NULL,
    color VARCHAR(32) NOT NULL,
    stock_quantity INT NOT NULL DEFAULT 0,
    unit VARCHAR(16) NOT NULL DEFAULT 'шт', -- шт, метр, компл.
    min_threshold INT NOT NULL DEFAULT 2,
    price NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    creator VARCHAR(64) DEFAULT '',
    create_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updater VARCHAR(64) DEFAULT '',
    update_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE UNIQUE INDEX uk_inventory_sku_active ON kings_inventory (sku) WHERE deleted = false;
CREATE INDEX idx_inventory_item_type ON kings_inventory (item_type);

CREATE TRIGGER trg_kings_inventory_update_time
    BEFORE UPDATE ON kings_inventory
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ------------------------------------------------------------------------------
-- 6. Table: kings_cash_account (Счета кассы: Сейф, POS-терминал, Банк)
-- ------------------------------------------------------------------------------
DROP TABLE IF EXISTS kings_cash_account CASCADE;
CREATE TABLE kings_cash_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    account_type VARCHAR(32) NOT NULL, -- CASH, POS, BANK
    balance NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(8) NOT NULL DEFAULT 'RUB',
    account_no VARCHAR(64) NULL,
    creator VARCHAR(64) DEFAULT '',
    create_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updater VARCHAR(64) DEFAULT '',
    update_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE TRIGGER trg_kings_cash_account_update_time
    BEFORE UPDATE ON kings_cash_account
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ------------------------------------------------------------------------------
-- 7. Table: kings_cash_transaction (Журнал движения денежных средств ДДС)
-- ------------------------------------------------------------------------------
DROP TABLE IF EXISTS kings_cash_transaction CASCADE;
CREATE TABLE kings_cash_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_no VARCHAR(64) NOT NULL,
    account_id BIGINT NOT NULL REFERENCES kings_cash_account(id) ON DELETE CASCADE,
    account_name VARCHAR(128) NOT NULL,
    type VARCHAR(16) NOT NULL, -- INCOME, EXPENSE
    category VARCHAR(64) NOT NULL, -- Предоплата, 100% Оплата, Закупка ткани, Оплата портному
    amount NUMERIC(14, 2) NOT NULL,
    related_order_no VARCHAR(64) NULL,
    operator_name VARCHAR(64) NOT NULL,
    comment TEXT DEFAULT '',
    creator VARCHAR(64) DEFAULT '',
    create_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updater VARCHAR(64) DEFAULT '',
    update_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX idx_cash_tx_account_id ON kings_cash_transaction (account_id);
CREATE INDEX idx_cash_tx_type ON kings_cash_transaction (type);
CREATE INDEX idx_cash_tx_create_time ON kings_cash_transaction (create_time);

CREATE TRIGGER trg_kings_cash_transaction_update_time
    BEFORE UPDATE ON kings_cash_transaction
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ------------------------------------------------------------------------------
-- 8. Table: kings_purchase (Закупки итальянских и английских тканей)
-- ------------------------------------------------------------------------------
DROP TABLE IF EXISTS kings_purchase CASCADE;
CREATE TABLE kings_purchase (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR(64) NOT NULL,
    supplier VARCHAR(128) NOT NULL,
    material_type VARCHAR(32) NOT NULL, -- FABRIC, LINING, BUTTONS, ACCESSORY
    material_name VARCHAR(256) NOT NULL,
    quantity NUMERIC(10, 2) NOT NULL,
    unit VARCHAR(16) NOT NULL DEFAULT 'м',
    price_per_unit NUMERIC(12, 2) NOT NULL,
    total_cost NUMERIC(14, 2) NOT NULL,
    payment_status VARCHAR(32) NOT NULL DEFAULT 'PAID', -- PAID, PARTIAL, UNPAID
    account_id BIGINT NULL REFERENCES kings_cash_account(id) ON DELETE SET NULL,
    paid_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    arrival_date DATE NULL,
    creator VARCHAR(64) DEFAULT '',
    create_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updater VARCHAR(64) DEFAULT '',
    update_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX idx_purchase_supplier ON kings_purchase (supplier);
CREATE INDEX idx_purchase_payment_status ON kings_purchase (payment_status);

CREATE TRIGGER trg_kings_purchase_update_time
    BEFORE UPDATE ON kings_purchase
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES ДЛЯ SUPABASE
-- Разрешаем доступ клиентам через anon-ключ (Vercel) и authenticated
-- ==============================================================================

ALTER TABLE sys_access_code ENABLE ROW LEVEL SECURITY;
ALTER TABLE sys_login_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE kings_client ENABLE ROW LEVEL SECURITY;
ALTER TABLE kings_order ENABLE ROW LEVEL SECURITY;
ALTER TABLE kings_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE kings_cash_account ENABLE ROW LEVEL SECURITY;
ALTER TABLE kings_cash_transaction ENABLE ROW LEVEL SECURITY;
ALTER TABLE kings_purchase ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for CRM access code users" ON sys_access_code FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for CRM login logs" ON sys_login_log FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for CRM clients" ON kings_client FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for CRM orders" ON kings_order FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for CRM inventory" ON kings_inventory FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for CRM cash accounts" ON kings_cash_account FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for CRM cash transactions" ON kings_cash_transaction FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for CRM purchases" ON kings_purchase FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ==============================================================================
-- НАЧАЛЬНЫЕ ДАННЫЕ (SEED DATA) ДЛЯ KINGSNAME CRM
-- ==============================================================================

-- 1. Коды доступа сотрудников
INSERT INTO sys_access_code (code, user_id, user_name, role_code, valid_type, expire_time, status, creator)
VALUES 
('88888888', 1, 'Шеф-Администратор KINGSNAME', 'admin', 3, NULL, 0, 'SYSTEM'),
('12345678', 2, 'Мансур (Консультант салона)', 'consultant', 1, timezone('utc'::text, now()) + interval '12 hours', 0, '88888888'),
('55555555', 3, 'Мастер-портной Адам', 'tailor', 2, timezone('utc'::text, now()) + interval '24 hours', 0, '88888888'),
('77777777', 4, 'Залина (Менеджер @kingsname)', 'manager', 3, NULL, 0, '88888888');

-- 2. Картотека VIP-клиентов
INSERT INTO kings_client (id, name, phone, city, instagram, vip_level, total_spent, notes)
VALUES
(1, 'Абубакар Кадыров', '+7 (928) 001-95-95', 'Грозный', '@abubakar_k', 3, 420000.00, 'Предпочитает шерсть Loro Piana Super 150s, приталенный силуэт Slim Fit, монограмма на подкладке.'),
(2, 'Магомед Даудов', '+7 (928) 111-22-33', 'Махачкала', '@magomed_d', 2, 235000.00, 'Классический крой Regular, пиджаки с широким заостренным лацканом Peak Lapel.'),
(3, 'Тимур Эдилов', '+7 (928) 222-33-44', 'Грозный', '@timur_e', 1, 95000.00, 'Заказчик смокинга Black Tie для торжественного мероприятия.'),
(4, 'Хамзат Батаев', '+7 (928) 333-44-55', 'Москва', '@khamzat_b', 2, 185000.00, 'Регулярные заказы сорочек ручной работы и пальто из кашемира.'),
(5, 'Ислам Юсупов', '+7 (928) 444-55-66', 'Дубай', '@islam_y', 3, 560000.00, 'Индивидуальный пошив костюмов-троек Scabal, шелковые подкладки с золотой нитью.');

-- 3. Счета кассы
INSERT INTO kings_cash_account (id, name, account_type, balance, currency, account_no)
VALUES
(1, 'Сейф салона (Наличные)', 'CASH', 1420000.00, 'RUB', 'SAFE-GROZNY-01'),
(2, 'POS-терминал / СБП (Эквайринг)', 'POS', 1980000.00, 'RUB', 'POS-KNG-9801'),
(3, 'Расчетный счет KINGSNAME (Банк)', 'BANK', 1450000.00, 'RUB', '40702810900000088888');

-- 4. Заказы Bespoke (Все 6 этапов воронки)
INSERT INTO kings_order 
(id, order_no, client_id, client_name, client_phone, channel, product_type, order_type, status, 
 height, chest, waist, hips, shoulder_width, sleeve_length, trouser_length, 
 fabric_brand, fabric_sku, fabric_color, lapel_type, fit_type, monogram, button_type, tailor_notes, 
 total_amount, deposit_amount, balance_amount, payment_method, payment_status, appointment_date, target_completion_date)
VALUES
-- Этап 1: LEAD (Лид из Instagram)
(1, 'KN-202609-001', 3, 'Тимур Эдилов', '+7 (928) 222-33-44', 'INSTAGRAM', 'Смокинг Black Tie', 'BESPOKE', 'LEAD',
 182, 104.0, 88.0, 102.0, 47.5, 64.0, 106.0,
 'Vitale Barberis Canonico', 'VBC-9021', 'Black Tie', 'Shawl', 'Slim Fit', 'T.E.', 'Satin Covered', 'Запрос из Direct @kingsname на пошив смокинга к свадьбе.',
 120000.00, 0.00, 120000.00, 'Карта', 'PENDING', timezone('utc'::text, now()) + interval '1 day', CURRENT_DATE + 14),

-- Этап 2: APPOINTMENT (Запись на примерку в салон)
(2, 'KN-202609-002', 4, 'Хамзат Батаев', '+7 (928) 333-44-55', 'WEBSITE', 'Пальто кашемировое', 'BESPOKE', 'APPOINTMENT',
 185, 108.0, 92.0, 105.0, 49.0, 66.0, 108.0,
 'Loro Piana', 'LP-CASHMERE-04', 'Charcoal Grey', 'Peak', 'Regular Classic', 'K.B.', 'Natural Horn', 'Запись через сайт kingsname.store. Примерка образцов кашемира в субботу.',
 180000.00, 0.00, 180000.00, 'Банковский перевод', 'PENDING', timezone('utc'::text, now()) + interval '2 days', CURRENT_DATE + 20),

-- Этап 3: FITTING (Снятие мерок)
(3, 'KN-202609-003', 2, 'Магомед Даудов', '+7 (928) 111-22-33', 'SALON_GROZNY', 'Костюм-двойка', 'BESPOKE', 'FITTING',
 178, 106.0, 94.0, 104.0, 48.0, 63.5, 102.0,
 'Scabal', 'SCABAL-ROYAL-77', 'Royal Navy', 'Peak', 'Regular Classic', 'M.D.', 'Natural Horn', 'Мерки сняты мастером Адамом. Учесть асимметрию правого плеча -0.5 см.',
 145000.00, 50000.00, 95000.00, 'Наличные', 'PARTIAL', timezone('utc'::text, now()), CURRENT_DATE + 10),

-- Этап 4: PAYMENT_AGREED (Внесена предоплата)
(4, 'KN-202609-004', 1, 'Абубакар Кадыров', '+7 (928) 001-95-95', 'SALON_GROZNY', 'Костюм-тройка', 'BESPOKE', 'PAYMENT_AGREED',
 184, 105.0, 86.0, 101.0, 47.0, 65.0, 107.0,
 'Loro Piana', 'LP-SUPER150-NAVY', 'Royal Navy', 'Notch', 'Slim Fit', 'A.K.', 'Mother of Pearl', 'Внесена предоплата 50%. Ткань отрезана со склада. Старт раскроя.',
 220000.00, 110000.00, 110000.00, 'Карта', 'PARTIAL', timezone('utc'::text, now()), CURRENT_DATE + 8),

-- Этап 5: TAILORING (В пошиве у мастера)
(5, 'KN-202609-005', 5, 'Ислам Юсупов', '+7 (928) 444-55-66', 'INSTAGRAM', 'Костюм-тройка с жилетом', 'BESPOKE', 'TAILORING',
 180, 102.0, 84.0, 99.0, 46.5, 63.0, 104.0,
 'Vitale Barberis Canonico', 'VBC-FLANNEL-33', 'Charcoal Grey', 'Peak', 'Bespoke Silhouette', 'I.Y.', 'Corozo', 'Сборка бортовой ткани вручную. Подготовка к промежуточной примерке.',
 195000.00, 100000.00, 95000.00, 'Банковский перевод', 'PARTIAL', timezone('utc'::text, now()), CURRENT_DATE + 5),

-- Этап 6: DELIVERED (Выдан клиенту)
(6, 'KN-202609-006', 1, 'Абубакар Кадыров', '+7 (928) 001-95-95', 'SALON_GROZNY', 'Классический пиджак RTW', 'RTW', 'DELIVERED',
 184, 105.0, 86.0, 101.0, 47.0, 65.0, 107.0,
 'Loro Piana', 'LP-RTW-JACKET', 'Твидовая клетка', 'Notch', 'Slim Fit', '', 'Natural Horn', 'Подогнан по фигуре в салоне. Выдан в фирменном чехле KINGSNAME.',
 85000.00, 85000.00, 0.00, 'Наличные', 'PAID', timezone('utc'::text, now()), CURRENT_DATE);

-- 5. Склад изделий и тканей
INSERT INTO kings_inventory (item_type, sku, name, size, height_category, color, stock_quantity, unit, min_threshold, price)
VALUES
('SUIT', 'KN-SUIT-BLK-48', 'Костюм-двойка Black Sartorial', '48', '176-182', 'Черный', 4, 'шт', 2, 75000.00),
('SUIT', 'KN-SUIT-BLK-50', 'Костюм-двойка Black Sartorial', '50', '176-182', 'Черный', 1, 'шт', 2, 75000.00),
('SUIT', 'KN-SUIT-NAV-52', 'Костюм-тройка Royal Navy Heritage', '52', '182-188', 'Royal Navy', 5, 'шт', 2, 95000.00),
('SUIT', 'KN-SUIT-GRY-54', 'Костюм-двойка Charcoal Wool', '54', '182-188', 'Charcoal Grey', 3, 'шт', 2, 82000.00),
('SUIT', 'KN-SUIT-TWD-50', 'Костюм твидовый English Tweed', '50', '176-182', 'Твидовая клетка', 2, 'шт', 2, 89000.00),
('FABRIC', 'FAB-LP-SUPER150', 'Ткань Loro Piana Super 150s Wool', NULL, NULL, 'Royal Navy', 42, 'метр', 10, 18000.00),
('FABRIC', 'FAB-VBC-130S', 'Ткань Vitale Barberis Canonico 130s', NULL, NULL, 'Черный', 65, 'метр', 15, 12000.00),
('FABRIC', 'FAB-SCABAL-CASH', 'Ткань Scabal Кашемир 100%', NULL, NULL, 'Charcoal Grey', 18, 'метр', 8, 28000.00),
('SHIRT', 'KN-SHIRT-WHT-40', 'Сорочка ручной работы Poplin White', '50', '176-182', 'Белый', 12, 'шт', 3, 16000.00),
('ACCESSORY', 'KN-ACC-TIE-GOLD', 'Галстук шелковый KINGSNAME Gold Accent', NULL, NULL, 'Gold/Navy', 15, 'шт', 5, 8500.00);

-- 6. Закупки итальянских тканей
INSERT INTO kings_purchase (invoice_no, supplier, material_type, material_name, quantity, unit, price_per_unit, total_cost, payment_status, account_id, paid_amount, arrival_date)
VALUES
('LP-2026-88', 'Loro Piana S.p.A. (Италия)', 'FABRIC', 'Шерсть Super 150s Tasmanian Navy Twill', 25.0, 'м', 15400.00, 385000.00, 'PAID', 3, 385000.00, CURRENT_DATE - 4),
('VBC-2026-04', 'Vitale Barberis Canonico (Италия)', 'FABRIC', 'Шерсть Super 130s Perennial Charcoal', 30.0, 'м', 9200.00, 276000.00, 'PAID', 3, 276000.00, CURRENT_DATE - 2),
('SC-2026-12', 'Scabal (Англия/Бельгия)', 'FABRIC', 'Diamond Chip Super 180s Midnight Blue', 15.0, 'м', 28000.00, 420000.00, 'PARTIAL', 3, 210000.00, CURRENT_DATE + 3);

-- 7. Движение денежных средств (ДДС)
INSERT INTO kings_cash_transaction (transaction_no, account_id, account_name, type, category, amount, related_order_no, operator_name, comment)
VALUES
('TX-2026-001', 2, 'POS-терминал / СБП (Эквайринг)', 'INCOME', 'Предоплата 50%', 120000.00, 'KN-202609-001', 'Шеф-Администратор', 'Предоплата за пошив костюма Loro Piana'),
('TX-2026-002', 1, 'Сейф салона (Наличные)', 'INCOME', '100% Оплата', 280000.00, 'KN-202609-002', 'Менеджер', 'Полный расчет за смокинг Black Tie Scabal'),
('TX-2026-003', 3, 'Расчетный счет KINGSNAME (Банк)', 'EXPENSE', 'Закупка ткани', 385000.00, 'LP-2026-88', 'Шеф-Администратор', 'Оплата инвойса Loro Piana S.p.A. (25м Super 150s Tasmanian)');

-- 8. Журнал авторизаций
INSERT INTO sys_login_log (code, user_name, role_code, ip, user_agent, result_status, result_msg, login_time)
VALUES
('88888888', 'Шеф-Администратор KINGSNAME', 'admin', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)', 1, 'Успешная авторизация по мастер-коду администратора', timezone('utc'::text, now()));

-- Синхронизация последовательностей ID (Identity sequences)
SELECT setval(pg_get_serial_sequence('sys_access_code', 'id'), coalesce(max(id), 1)) FROM sys_access_code;
SELECT setval(pg_get_serial_sequence('kings_client', 'id'), coalesce(max(id), 1)) FROM kings_client;
SELECT setval(pg_get_serial_sequence('kings_order', 'id'), coalesce(max(id), 1)) FROM kings_order;
SELECT setval(pg_get_serial_sequence('kings_inventory', 'id'), coalesce(max(id), 1)) FROM kings_inventory;
SELECT setval(pg_get_serial_sequence('kings_cash_account', 'id'), coalesce(max(id), 1)) FROM kings_cash_account;
SELECT setval(pg_get_serial_sequence('kings_cash_transaction', 'id'), coalesce(max(id), 1)) FROM kings_cash_transaction;
SELECT setval(pg_get_serial_sequence('kings_purchase', 'id'), coalesce(max(id), 1)) FROM kings_purchase;
SELECT setval(pg_get_serial_sequence('sys_login_log', 'id'), coalesce(max(id), 1)) FROM sys_login_log;
